spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sns:
        endpoint: ${AWS_SNS_ENDPOINT}
        region: ${AWS_SNS_REGION}
server:
  port: 8081
com:
  christmas:
    letter:
      aws:
        sns:
          topic: ${AWS_SNS_TOPIC_ARN}