services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG:-1}
    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
      - './docker-local/localstack/localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh'
