package com.christmas.letter.model;

import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.util.List;

@Data
@DynamoDbBean
public class ChristmasLetterEntity {

    private String id;
    private String email;
    private String name;
    private List<String> wishes;
    private String deliveryAddress;

    @DynamoDbPartitionKey
    @DynamoDbAutoGeneratedUuid
    public String getId() {
        return id;
    }

}
