spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      dynamodb:
        region: ${AWS_SQS_REGION}
        url: ${AWS_DYNAMODB_URL}
server:
  port: 8083

security:
  jwt:
    secret-key: ""
    expiration-time: ""
