spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      dynamodb:
        region: ${AWS_DYNAMODB_REGION}
        url: ${AWS_DYNAMODB_URL}
server:
  port: 8083

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 1800000
