spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sqs:
        region: ${AWS_SQS_REGION}
        endpoint: http://localhost:4566
      dynamodb:
        region: ${AWS_SQS_REGION}
        url: ${AWS_DYNAMODB_URL}
server:
  port: 8082

com:
  christmas:
    letter:
      aws:
        sqs:
          queue-url: ${AWS_SQS_QUEUE_URL}
          queue-name: ${AWS_SQS_QUEUE_NAME}
